version: '3.8'

services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        env_file: .env
        environment:
            - POSTGRES_HOST=postgres
        ports:
            - ${API_PORT}:${API_PORT}

    postgres:
        image: postgres:12
        env_file: .env
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
